version: '3.9'

services:
  nextjs:
    container_name: journaling-ui-app-with-local-backend
    build: .
    ports:
      - 3006:3006
    volumes:
      - .:/app
    environment:
      BACKEND_URL: http://springboot:8080
    entrypoint: /bin/sh -c "npm install && npm run dev"
    networks:
    - journaling-app

networks:
  journaling-app:
    external: true