version: '3.9'

services:
  nextjs:
    container_name: journaling-ui-app-nextjs
    build: .
    ports:
      - 3001:3001
    volumes:
      - .:/app
    entrypoint: /bin/sh -c "npm install && npm run dev"

  nextjs-prod:
    container_name: journaling-ui-app-nextjs-prod
    build: .
    ports:
      - 3001:3001
    volumes:
      - .:/app
    entrypoint: /bin/sh -c "npm install && npm run build && npm run start"

  mock-api:
    container_name: journaling-ui-app-mock-api
    build: .
    volumes:
      - ./:/app
    entrypoint: /bin/sh -c "npm install && npm run mock"
    ports:
      - 3000:3000
