version: '3.9'

services:
  nextjs:
    container_name: journaling-ui-app
    build: .
    ports:
      - 3006:3006
    volumes:
      - .:/app
    environment:
      BACKEND_URL: http://springboot:8080
    entrypoint: /bin/sh -c "npm install && npm run build && npm run start"
    networks:
    - journaling-back-end_journaling-app 

networks:
  journaling-app:
    external: true