import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import { withPageAuthRequired } from '@auth0/nextjs-auth0/client'
import { useNotes } from '@/hooks/useNotes'
import { useEffect, useState } from 'react'
import DesktopApp from '@/components/DesktopApp'
import MobileApp from '@/components/MobileApp'

const inter = Inter({ subsets: ['latin'] })

export interface Note {
  id: string;
  text: string;
  datetime: string;
}

export default withPageAuthRequired(function Home() {

  const [isMobile, setIsMobile] = useState(false);
  useEffect(() => {
    if (window.innerWidth < 768) {
      setIsMobile(true);
    }
  }, []);


  return (
    <>
      <Head>
        <title>My thoughts</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/journaling_icon.ico" />
      </Head>
      <main className={styles.main}>
        {
          isMobile ?
            <MobileApp />
            :
            <DesktopApp />
        }
      </main>
    </>
  )
})
